import Link from "next/link";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service — Varant",
  description:
    "Terms of Service for Varant — the ancient council for modern bets. Read our terms before beginning your Vichar.",
};

export default function TermsPage() {
  return (
    <main className="bg-[#F5F2EC] text-[#1A1510] font-[family-name:var(--font-inter)] min-h-screen relative overflow-x-hidden">
      {/* Background Textures */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="varant-mesh-grad"></div>
        <div className="varant-grain-overlay"></div>
      </div>

      {/* Back Navigation */}
      <nav className="relative z-10 pt-8 px-6 md:px-12 max-w-4xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-[#767676] hover:text-[#9B1C1C] transition-colors group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          <span className="font-medium">Back to Varant</span>
        </Link>
      </nav>

      {/* Content */}
      <article className="relative z-10 max-w-4xl mx-auto px-6 md:px-12 pt-16 pb-32">
        {/* Header */}
        <div className="mb-16">
          <span className="inline-block text-[10px] font-semibold tracking-[0.2em] text-[#9B1C1C] uppercase mb-4">
            Vidhi · विधि
          </span>
          <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-5xl lg:text-[56px] leading-[1.1] text-[#1A1510] mb-6">
            Terms of Service
          </h1>
          <p className="text-[#666] text-lg font-light leading-relaxed max-w-2xl">
            By using Varant, you convene a Sabha — a deliberate act of
            structured reasoning. These terms govern that engagement.
          </p>
          <p className="text-[12px] text-[#999] mt-4 uppercase tracking-widest">
            Effective: March 2026
          </p>
        </div>

        {/* Divider */}
        <div className="h-px w-full varant-jali-border mb-16"></div>

        {/* Terms Sections */}
        <div className="space-y-14">
          {/* 1. Service Description */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">01</span>
              Service Description
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              Varant is an AI-powered deliberation platform inspired by the ancient Indian Sabha tradition.
              It convenes four named AI personas — <strong className="text-[#1A1510] font-medium">Vitarka</strong> (Skeptic),{" "}
              <strong className="text-[#1A1510] font-medium">Asha</strong> (Optimist),{" "}
              <strong className="text-[#1A1510] font-medium">Yukti</strong> (Pragmatist), and{" "}
              <strong className="text-[#1A1510] font-medium">Vipaksha</strong> (Devil&apos;s Advocate) — to debate
              your decision across three structured rounds (Pratham Paksha, Khandana, Nirnaya)
              before delivering a final verdict with a Matra (confidence score).
            </p>
          </section>

          {/* 2. Nature of Output */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">02</span>
              Nature of Output
            </h2>
            <div className="bg-white/60 backdrop-blur-sm border border-[#E8E3DC] rounded-2xl p-6 mb-4">
              <p className="text-[15px] text-[#555] leading-relaxed">
                <strong className="text-[#9B1C1C] font-semibold">Important Disclaimer:</strong>{" "}
                Varant is a <strong className="text-[#1A1510] font-medium">deliberation tool</strong>,
                not a provider of professional advice. All outputs — including the Nirnaya (verdict),
                Shastra (decision memo), and Matra (confidence score) — are generated by artificial
                intelligence and should not be treated as legal, financial, medical, or professional guidance.
              </p>
            </div>
            <p className="text-[15px] text-[#555] leading-relaxed">
              The personas argue fixed philosophical positions designed to expose multiple
              angles of your decision. They are not trained professionals, and their arguments
              are not optimized for accuracy. You are solely responsible for any decisions you
              make based on your Vichar sessions.
            </p>
          </section>

          {/* 3. AI-Generated Content */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">03</span>
              AI-Generated Content
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              All Sabha deliberations are generated by multiple AI language models routed
              through the OpenRouter API. These models include Google Gemini Flash, OpenAI
              GPT-4.1 Nano, Alibaba Qwen 3.5 Flash, and Google Gemini Flash Lite. AI-generated
              content may contain errors, inconsistencies, or inaccuracies. Varant does not
              guarantee the factual correctness of any output.
            </p>
          </section>

          {/* 4. Acceptable Use */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">04</span>
              Acceptable Use
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed mb-4">
              You agree to use Varant only for its intended purpose: structured deliberation
              on decisions. You may not:
            </p>
            <ul className="space-y-2 text-[15px] text-[#555] leading-relaxed pl-6">
              <li className="relative before:content-['✦'] before:absolute before:-left-5 before:text-[#D97706] before:text-[12px]">
                Attempt to extract, reverse-engineer, or misuse the system prompts or persona architecture
              </li>
              <li className="relative before:content-['✦'] before:absolute before:-left-5 before:text-[#D97706] before:text-[12px]">
                Use the platform to generate harmful, abusive, or illegal content
              </li>
              <li className="relative before:content-['✦'] before:absolute before:-left-5 before:text-[#D97706] before:text-[12px]">
                Overload the service with automated requests or scraping
              </li>
              <li className="relative before:content-['✦'] before:absolute before:-left-5 before:text-[#D97706] before:text-[12px]">
                Misrepresent Varant&apos;s outputs as professional advice to third parties
              </li>
            </ul>
          </section>

          {/* 5. Intellectual Property */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">05</span>
              Intellectual Property
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              The Varant brand, Sanskrit identity system (including the names Vichar, Sabha,
              Prashna, Shastra, Smriti, Mimamsa, Matra, and Sangharsha as used in the product),
              persona architecture, and deliberation protocol are proprietary to Varant.
              The decisions and reasoning you input belong to you — we claim no ownership
              over your questions or context.
            </p>
          </section>

          {/* 6. Third-Party Services */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">06</span>
              Third-Party Services
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              Varant relies on the OpenRouter API for multi-model AI routing. Your use of
              Varant is also subject to OpenRouter&apos;s terms of service and privacy policy. We
              are not responsible for outages, rate limits, or policy changes imposed by
              third-party AI providers.
            </p>
          </section>

          {/* 7. Limitation of Liability */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">07</span>
              Limitation of Liability
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              Varant is provided &quot;as is&quot; without warranties of any kind. We are not liable
              for any direct, indirect, incidental, or consequential damages arising from
              your use of the platform or from decisions made using Varant&apos;s outputs. The
              Sabha deliberates. What you do with the Nirnaya is <em className="font-[family-name:var(--font-lora)] text-[#767676]">your vara</em>.
            </p>
          </section>

          {/* 8. Pricing & Free Tier */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">08</span>
              Pricing &amp; Access
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              Varant currently operates in a free beta. Future pricing tiers (Free, Pro, Team,
              and Enterprise) may be introduced. Any changes to pricing or access will be
              communicated in advance. Current estimated cost per session is approximately
              $0.0006, borne entirely by Varant during the beta period.
            </p>
          </section>

          {/* 9. Changes to Terms */}
          <section>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-semibold mb-4 flex items-baseline gap-3">
              <span className="text-[11px] font-mono tracking-widest text-[#D97706]">09</span>
              Changes to Terms
            </h2>
            <p className="text-[15px] text-[#555] leading-relaxed">
              We may update these terms as the product evolves. Changes will be reflected on
              this page with an updated effective date. Continued use of Varant after changes
              constitutes acceptance of the new terms.
            </p>
          </section>
        </div>

        {/* Closing */}
        <div className="mt-24 pt-12 border-t border-[#E8E3DC]">
          <p className="text-sm text-[#999] font-light leading-relaxed">
            Questions about these terms? Visit our{" "}
            <Link href="/contact" className="text-[#9B1C1C] hover:text-[#D97706] transition-colors underline underline-offset-2">
              contact page
            </Link>
            .
          </p>
        </div>
      </article>
    </main>
  );
}
